<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="2" failed="1" ignored="0" total="4" passed="1">
  <reporter-output>
  </reporter-output>
  <suite name="Suite" duration-ms="51115" started-at="2019-05-29T00:18:24Z" finished-at="2019-05-29T00:19:15Z">
    <groups>
    </groups>
    <test name="Test" duration-ms="51115" started-at="2019-05-29T00:18:24Z" finished-at="2019-05-29T00:19:15Z">
      <class name="com.selenium.pageObject.test.TestLogin">
        <test-method status="PASS" signature="beforeSuite()[pri:0, instance:com.selenium.pageObject.test.TestLogin@1060b431]" name="beforeSuite" is-config="true" duration-ms="2455" started-at="2019-05-29T00:18:21Z" finished-at="2019-05-29T00:18:24Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeSuite -->
        <test-method status="PASS" signature="beforeMethod()[pri:0, instance:com.selenium.pageObject.test.TestLogin@1060b431]" name="beforeMethod" is-config="true" duration-ms="7174" started-at="2019-05-29T00:18:24Z" finished-at="2019-05-29T00:18:32Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeMethod -->
        <test-method status="SKIP" signature="test(java.lang.String, java.lang.String, java.lang.String)[pri:0, instance:com.selenium.pageObject.test.TestLogin@1060b431]" name="test" duration-ms="5698" started-at="2019-05-29T00:18:32Z" data-provider="loginData" finished-at="2019-05-29T00:18:37Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[zhangsan]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[123456.0]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[登录成功]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [登录成功] but found [用户名或密码错误]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [登录成功] but found [用户名或密码错误]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:137)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:453)
at org.testng.Assert.assertEquals(Assert.java:463)
at com.selenium.pageObject.LoginPage.check_login_result(LoginPage.java:47)
at com.selenium.pageObject.test.TestLogin.test(TestLogin.java:26)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- test -->
        <test-method status="PASS" signature="afterMethod()[pri:0, instance:com.selenium.pageObject.test.TestLogin@1060b431]" name="afterMethod" is-config="true" duration-ms="439" started-at="2019-05-29T00:18:37Z" finished-at="2019-05-29T00:18:38Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterMethod -->
        <test-method status="PASS" signature="beforeMethod()[pri:0, instance:com.selenium.pageObject.test.TestLogin@1060b431]" name="beforeMethod" is-config="true" duration-ms="7910" started-at="2019-05-29T00:18:38Z" finished-at="2019-05-29T00:18:46Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeMethod -->
        <test-method status="SKIP" signature="test(java.lang.String, java.lang.String, java.lang.String)[pri:0, instance:com.selenium.pageObject.test.TestLogin@1060b431]" name="test" duration-ms="3250" started-at="2019-05-29T00:18:46Z" data-provider="loginData" finished-at="2019-05-29T00:18:49Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[zhangsan]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[123456.0]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[登录成功]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [登录成功] but found [用户名或密码错误]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [登录成功] but found [用户名或密码错误]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:137)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:453)
at org.testng.Assert.assertEquals(Assert.java:463)
at com.selenium.pageObject.LoginPage.check_login_result(LoginPage.java:47)
at com.selenium.pageObject.test.TestLogin.test(TestLogin.java:26)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.retryFailed(Invoker.java:838)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1009)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- test -->
        <test-method status="PASS" signature="afterMethod()[pri:0, instance:com.selenium.pageObject.test.TestLogin@1060b431]" name="afterMethod" is-config="true" duration-ms="379" started-at="2019-05-29T00:18:49Z" finished-at="2019-05-29T00:18:49Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterMethod -->
        <test-method status="PASS" signature="beforeMethod()[pri:0, instance:com.selenium.pageObject.test.TestLogin@1060b431]" name="beforeMethod" is-config="true" duration-ms="7725" started-at="2019-05-29T00:18:50Z" finished-at="2019-05-29T00:18:57Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeMethod -->
        <test-method status="FAIL" signature="test(java.lang.String, java.lang.String, java.lang.String)[pri:0, instance:com.selenium.pageObject.test.TestLogin@1060b431]" name="test" duration-ms="2688" started-at="2019-05-29T00:18:57Z" data-provider="loginData" finished-at="2019-05-29T00:19:00Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[zhangsan]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[123456.0]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[登录成功]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [登录成功] but found [用户名或密码错误]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [登录成功] but found [用户名或密码错误]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:137)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:453)
at org.testng.Assert.assertEquals(Assert.java:463)
at com.selenium.pageObject.LoginPage.check_login_result(LoginPage.java:47)
at com.selenium.pageObject.test.TestLogin.test(TestLogin.java:26)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.retryFailed(Invoker.java:838)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1009)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- test -->
        <test-method status="PASS" signature="afterMethod()[pri:0, instance:com.selenium.pageObject.test.TestLogin@1060b431]" name="afterMethod" is-config="true" duration-ms="181" started-at="2019-05-29T00:19:01Z" finished-at="2019-05-29T00:19:01Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterMethod -->
        <test-method status="PASS" signature="beforeMethod()[pri:0, instance:com.selenium.pageObject.test.TestLogin@1060b431]" name="beforeMethod" is-config="true" duration-ms="8256" started-at="2019-05-29T00:19:01Z" finished-at="2019-05-29T00:19:09Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeMethod -->
        <test-method status="PASS" signature="test(java.lang.String, java.lang.String, java.lang.String)[pri:0, instance:com.selenium.pageObject.test.TestLogin@1060b431]" name="test" duration-ms="5579" started-at="2019-05-29T00:19:09Z" data-provider="loginData" finished-at="2019-05-29T00:19:15Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[zhangsan11]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[123456.0]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[用户名或密码错误]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- test -->
        <test-method status="PASS" signature="afterMethod()[pri:0, instance:com.selenium.pageObject.test.TestLogin@1060b431]" name="afterMethod" is-config="true" duration-ms="71" started-at="2019-05-29T00:19:15Z" finished-at="2019-05-29T00:19:15Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterMethod -->
        <test-method status="PASS" signature="afterSuite()[pri:0, instance:com.selenium.pageObject.test.TestLogin@1060b431]" name="afterSuite" is-config="true" duration-ms="825" started-at="2019-05-29T00:19:15Z" finished-at="2019-05-29T00:19:16Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterSuite -->
      </class> <!-- com.selenium.pageObject.test.TestLogin -->
    </test> <!-- Test -->
  </suite> <!-- Suite -->
</testng-results>
